text = '''NAANNAAN NAAANNAA NAANANNN NAANANNA NAANNANN NAANNANN NAANNANA NAANAAAN
NAANNNAN NAANANNA NAANAAAN NAANNNNA NAAANNAA NAANNNAA NAANANNA
NAANANNA NAANNNAA NAAAANNA NAANNNAN NAANNANA NAAANNAN'''.replace(' ','').replace('\n','').replace('N','0').replace('A','1')

print hex(int(text,2))[2:-1].decode('hex')